# Generated by Django 3.2.12 on 2022-07-02 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=5000)),
                ('image', models.ImageField(upload_to='movie')),
                ('kinopoisk_id', models.IntegerField()),
            ],
        ),
    ]
